---
title: "clase 6"
output: html_notebook
---

```{r}
library(pracma)
library(Smisc)
library(caret)
```

```{r}


A <- matrix(c(1, 0, 0, 0, 0, 1, 0, 1300,
              1, -1, 0, 0, 0, 0, 1, 200,
              0, 1, 0, 0, -1, 0, 0, 200,
              0, 0, 0, -1, 1, 0, 0, 400,
              0, 0, 1, -1, 0, 0, 1, 100,
              0, 0, 1, 0, 0, 1, 0, 600), 6, 8, byrow=T)

A

rref(A)
```


Vectores li

```{r}
y <- matrix(c(1,3,4,2,6,8,7,2,9,4,1,7,3.5,1,4.5), ncol=3, byrow=T)
y

findDepMat(y)
findDepMat(y, rows = F)
```


linealmente dependiente e independiente

```{r}
ejemplo <-matrix(c(1,-2,3,2,-2,0,0,1,7),3,3)
rref(ejemplo)
Rank(ejemplo)
det(ejemplo)
findLinearCombos(ejemplo)
```

```{r}
ejemplo2 <-matrix(c(1,3,11,-3,0,-6,0,4,12),3,3)
rref(ejemplo2)
Rank(ejemplo2)
det(ejemplo2)
# devuelve algo si es ld
findLinearCombos(ejemplo2)

```

```{r}
m2 <- matrix(c(1,2,2,5,4,-3), ncol=2, byrow=T)
m2
Rank(m2)
rref(m2)
```


valores y vectores propios

```{r}
A <- matrix(c(10,-18,6,-11), 2, 2, byrow=T)

A

v1 <- matrix(c(2,1), 2,1)

v1

v2 <- matrix(c(3,2), 2,1)

v2

identical(A %*% v1,v1)
identical(A %*% v2, -2*v2)

all.equal(A %*% v1,v1)
all.equal(A %*% v2, -2*v2)

A %*% v2 == -2*v2

```


eig(a): vector de valores propios del paquete pracma
eigen(a) funciones base d R
```{r}
# nos da un vector que tiene los valores propios
eig(A)

eigen(A)

```


```{r}
A1 <- matrix(c(2,5,6,0,-3,2,0,0,5), 3,3, byrow=T)
A1
eigen(A1)$values
```

```{r}

A2 <-matrix(c(1,-1,4,3,2,-1,2,1,-1),3,3, byrow = T)
A2

C <- matrix(c(-1,1,1,4,-1,2,1,-1,1),3,3, byrow = T)

C

solve(C) %*% (A2 %*% C)

```